# Generated by Django 5.1.4 on 2024-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('academicyear', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('coursecode', models.CharField(max_length=20)),
                ('coursetitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course_table',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultyid', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=10)),
                ('emai', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='RCEE', max_length=100)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'faculty_table',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentid', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('emai', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='RCEE', max_length=100)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'student_table',
            },
        ),
    ]
