# Generated by Django 5.1.4 on 2024-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emai',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE(Regular)', 'CSE(R)'), ('CSE(HONORS)', 'CSE(H)'), ('CSE(IT)', 'CSIT'), ('ECE', 'ECE')], max_length=100),
        ),
    ]
