# Generated by Django 5.1.4 on 2024-12-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_emai_student_email_alter_course_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='emai',
            new_name='email',
        ),
    ]
