# Generated by Django 5.1.4 on 2024-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_emai_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academicyear',
            field=models.CharField(choices=[(-1, -1), (-1, -1), (-1, -1)], max_length=20),
        ),
    ]
