# Generated by Django 5.1.4 on 2024-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_course_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academicyear',
            field=models.CharField(choices=[('2024-2025', '2024-2025'), ('2023-2024', '2023-2024'), ('2022-2023', '2022-2023')], max_length=20),
        ),
    ]
