# Generated by Django 5.1.4 on 2025-01-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycoursemapping',
            name='component',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('S', 'Skilling')], default='L', max_length=10),
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='section',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
