# Generated by Django 5.1.4 on 2025-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_facultycoursemapping_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='component',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Practical', 'Practical'), ('Skilling', 'Skilling')], default='L', max_length=10),
        ),
    ]
